- leafletOsmId: "Andirika-Carto"
  code: "A"
  layerId: "andirika"
  nameId: "andirika"
  tileUrl: "https://tiles.andirika-osm.lem/tile/{z}/{x}/{y}.png?utm_source=railsport.andirika-osm.lem"
  maxZoom: 19
  canDownloadImage: true 
  canEmbed: true
  credit:
    id: "lemuria_credit_andirika_carto"
    donate: false

- leafletOsmId: "Mapnik"
  code: "M"
  layerId: "mapnik"
  nameId: "earth"
  wiki: "https://wiki.openstreetmap.org/wiki/OpenStreetMap_Carto"
  canEmbed: true
  canDownloadImage: true
  maxZoom: 19
  tileUrl: "https://tile.openstreetmap.org/{z}/{x}/{y}.png"
  credit:
    id: "openstreetmap_contributors"
    href: "https://supporting.openstreetmap.org"
    donate: true

